### ISSUE TITLE
Can't open .. starthinker/task/itp_audit/run.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by nmaiese** [google/starthinker#34]
When I trying to run ITP Audit Dashboard 2020 through UI Enterprise at the last step i receive this error: 

itp_audit - 1
**JOB_ERROR** 

"home/aniello_maiese/starthinker_virtualenv/bin/python: can't open file '/home/aniello_maiese/starthinker/task/itp_audit/run.py': [Errno 2] No such file or directory

**Comment by johnTerwilleger** [comment]
Is this issue still persisting? If so you can try doing a git pull on the repo and then assuring that this file is in your directory.
starthinker/task/itp_audit/run.py
