### ISSUE TITLE
Not able to get passed generating /starthinker_assets/service.json

### ISSUE THREAD

**Issue by toddheslin** [google/starthinker#47]
Hey team, I'm super excited about this project (just found it!) But I've spent a few hours debugging why I can't get passed any step where it checks for `/starthinker_assets/service.json`. 

I'm seeing:

```
created key [xxxxxxxxxxxxxxxxxx] of type [json] as [/Users/todd/Github/open-source/starthinker/starthinker_assets/service.json] for [starthinker@xxxxxxxxxxxxxxxxxxxxx.iam.gserviceaccount.com]
Failed To Create Service Credentials, Fix Then Run This Script Again
 1. Check permissions of gcloud user.
 2. Check if service accounts are enabled for the project.
 3. Manually paste service JSON credentials into: /starthinker_assets/service.json
```

I see `/starthinker_assets/service.json` is created and then deleted again. I'm running this using the correct GCP IAM project in scope and I'm a full-access project owner. I've manually run all of these and none cause errors:

https://github.com/google/starthinker/blob/master/install/config.sh#L596-L599

https://github.com/google/starthinker/blob/master/install/config.sh#L596-L599

https://github.com/google/starthinker/blob/master/install/config.sh#L596-L599

I'm unsure what the script is expecting to not error out. Any pointers would be super appreciated.

Thanks so much

**Comment by pkenjora** [comment]
Hi,

There was a bug briefly in the code that failed to detect existence of starthinker_assets/service.json.
[This line](https://github.com/google/starthinker/blob/master/install/config.sh#L634) was missing the ! (not) operator.

It has been patched, we are running tests today to verify the entire install process. A git pull should resolve it.

Regards,

- Paul

**Comment by toddheslin** [comment]
Perfect. All fixed now. Thanks Paul.
