### ISSUE TITLE
Error When Running Create IO Preview

### ISSUE THREAD

**Issue by natstavn** [google/starthinker#50]
Running the IO preview leads to the following errors.  The recipe settings are against my own project with all user toggles selected.

Hour | Task | Output / Error
-- | -- | --
done_outline     10 | dataset - 1   JOB_END   7 Minutes Ago | TASK: dataset   DATE: 2021-04-16   HOUR: 10   DATASET   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   DATASET CLEAR   DATASET CREATE   DATASET ACCESS
done_outline     10 | drive - 1   JOB_END   6 Minutes Ago | TASK: drive   DATE: 2021-04-16   HOUR: 10   Drive   Drive Copy https://docs.google.com/spreadsheets/d/1HZ2yU9hAnQgu7K74aYtRaw9hH-vtv9BV7iqQTngCbks   IO Preview Create IO Preview - Nate Training   Drive: File exists.
error     10 | sheets - 1   JOB_ERROR   6 Minutes Ago | TASK: sheets   DATE: 2021-04-16   HOUR: 10   SHEETS   SHEETS READ IO Preview Create IO   Preview - Nate Training IO Rules A1:P   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/sheets/run.py", line 143, in   <module>       sheets()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/sheets/run.py", line 102, in sheets       project.task['tab'],   project.task.get('range', 'A1'))     File   "/home/cjones8/starthinker/util/sheets/__init__.py", line 98, in   sheets_read         range=sheets_tab_range(sheet_tab, sheet_range)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1_6bcW1bqfyH4qqVMK2Ul9kV7JIA3qqYrDPKlqYmk6bc/values/IO%20Rules%21A1%3AP?alt=json   returned "Unable to parse range: IO Rules!A1:P". Details: "Unable   to parse range: IO Rules!A1:P">
error     10 | sheets - 2   JOB_ERROR   6 Minutes Ago | TASK: sheets   DATE: 2021-04-16   HOUR: 10   SHEETS   SHEETS READ IO Preview Create IO   Preview - Nate Training Excludes A1:B   Traceback (most recent call last):     File "/home/cjones8/starthinker/task/sheets/run.py",   line 143, in <module>       sheets()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/sheets/run.py", line 102, in sheets         project.task['tab'], project.task.get('range', 'A1'))     File   "/home/cjones8/starthinker/util/sheets/__init__.py", line 98, in   sheets_read         range=sheets_tab_range(sheet_tab, sheet_range)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1_6bcW1bqfyH4qqVMK2Ul9kV7JIA3qqYrDPKlqYmk6bc/values/Excludes%21A1%3AB?alt=json   returned "Unable to parse range: Excludes!A1:B". Details:   "Unable to parse range: Excludes!A1:B">
error     10 | google_api - 1   JOB_ERROR   6 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API dfareporting v3.4   campaigns.list   DISCOVERY FETCH: https://dfareporting.googleapis.com/$discovery/rest?version=v3.4&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/google_api/run.py", line 381, in   <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File   "/home/cjones8/starthinker/util/data/__init__.py", line 177, in   get_rows       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows         projectId=project_id, body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US">
error     10 | google_api - 2   JOB_ERROR   6 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API dfareporting v3.4   sites.list   DISCOVERY FETCH: https://dfareporting.googleapis.com/$discovery/rest?version=v3.4&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File "/home/cjones8/starthinker/task/google_api/run.py",   line 381, in <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File   "/home/cjones8/starthinker/util/data/__init__.py", line 177, in   get_rows       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows       projectId=project_id,   body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules was   not found in location US">
error     10 | google_api - 3   JOB_ERROR   5 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API dfareporting v3.4   advertisers.list   DISCOVERY FETCH: https://dfareporting.googleapis.com/$discovery/rest?version=v3.4&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/google_api/run.py", line 381, in   <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File   "/home/cjones8/starthinker/util/data/__init__.py", line 177, in   get_rows       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows         projectId=project_id, body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US">
error     10 | google_api - 4   JOB_ERROR   5 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API dfareporting v3.4   placements.list   DISCOVERY FETCH: https://dfareporting.googleapis.com/$discovery/rest?version=v3.4&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File "/home/cjones8/starthinker/task/google_api/run.py",   line 381, in <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File   "/home/cjones8/starthinker/util/data/__init__.py", line 177, in   get_rows       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows       projectId=project_id,   body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US">
error     10 | google_api - 5   JOB_ERROR   5 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API dfareporting v3.4   placementGroups.list   DISCOVERY FETCH: https://dfareporting.googleapis.com/$discovery/rest?version=v3.4&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/google_api/run.py", line 381, in   <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File "/home/cjones8/starthinker/util/data/__init__.py",   line 177, in get_rows       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows         projectId=project_id, body=body).execute()     File "/home/cjones8/starthinker/util/google_api/__init__.py",   line 386, in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US">
error     10 | google_api - 6   JOB_ERROR   5 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API displayvideo v1   advertisers.campaigns.list   DISCOVERY FETCH: https://displayvideo.googleapis.com/$discovery/rest?version=v1&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/google_api/run.py", line 381, in   <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File   "/home/cjones8/starthinker/util/data/__init__.py", line 177, in   get_rows       for row in rows:     File "/home/cjones8/starthinker/util/bigquery/__init__.py",   line 760, in query_to_rows         projectId=project_id, body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry      data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return wrapped(*args,   **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US">
error     10 | google_api - 7   JOB_ERROR   4 Minutes Ago | TASK: google_api   DATE: 2021-04-16   HOUR: 10   GOOGLE_API displayvideo v1   advertisers.insertionOrders.list   DISCOVERY FETCH: https://displayvideo.googleapis.com/$discovery/rest?version=v1&key=   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File "/home/cjones8/starthinker/task/google_api/run.py",   line 381, in <module>       google_api()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/google_api/run.py", line 374, in   google_api       for kwargs in   kwargs_list:     File   "/home/cjones8/starthinker/util/data/__init__.py", line 177, in   get_rows       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows       projectId=project_id,   body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules was   not found in location US">
error     10 | bigquery - 1   JOB_ERROR   4 Minutes Ago | TASK: bigquery   DATE: 2021-04-16   HOUR: 10   QUERY TO VIEW DV_IO_Insert_Review   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 262, in <module>       bigquery()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 255, in   bigquery       bigquery_query()     File "/home/cjones8/starthinker/task/bigquery/run.py",   line 222, in bigquery_query         project.Project.task['to'].get('replace', False)     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 275, in   query_to_view         projectId=project_id, datasetId=dataset_id, body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/datasets/Create_IO_Preview___Nate_Training/tables?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules".   Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules">
error     10 | bigquery - 2   JOB_ERROR   4 Minutes Ago | TASK: bigquery   DATE: 2021-04-16   HOUR: 10   QUERY TO VIEW DV_IO_Insert_Audit   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 262, in   <module>       bigquery()     File "/home/cjones8/starthinker/util/project/__init__.py",   line 475, in from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 255, in   bigquery       bigquery_query()     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 222, in   bigquery_query         project.Project.task['to'].get('replace', False)     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 275, in   query_to_view         projectId=project_id, datasetId=dataset_id, body=body).execute()     File "/home/cjones8/starthinker/util/google_api/__init__.py",   line 386, in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/datasets/Create_IO_Preview___Nate_Training/tables?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules".   Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.SHEET_Rules">
error     10 | bigquery - 3   JOB_ERROR   4 Minutes Ago | TASK: bigquery   DATE: 2021-04-16   HOUR: 10   QUERY TO SHEET IO Preview Create IO   Preview - Nate Training   SHEETS CLEAR IO Preview Create IO   Preview - Nate Training Audit A2   SHEETS WRITE IO Preview Create IO   Preview - Nate Training Audit A2   BIGQUERY QUERY: sc-amea-usr-starthin-natstavn   Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 262, in   <module>       bigquery()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 255, in   bigquery       bigquery_query()     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 184, in   bigquery_query       rows     File "/home/cjones8/starthinker/util/sheets/__init__.py",   line 116, in sheets_write       body = {'values':   list(data)}     File   "/home/cjones8/starthinker/util/csv/__init__.py", line 245, in   rows_to_type       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows         projectId=project_id, body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File "/home/cjones8/starthinker/util/google_api/__init__.py",   line 91, in API_Retry       data =   job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return wrapped(*args,   **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.DV_IO_Insert_Audit   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.DV_IO_Insert_Audit   was not found in location US">
error     10 | bigquery - 4   JOB_ERROR   3 Minutes Ago | TASK: bigquery   DATE: 2021-04-16   HOUR: 10   QUERY TO SHEET IO Preview Create IO   Preview - Nate Training   SHEETS CLEAR IO Preview Create IO   Preview - Nate Training IO Preview A2   SHEETS WRITE IO Preview Create IO   Preview - Nate Training IO Preview A2   BIGQUERY QUERY:   sc-amea-usr-starthin-natstavn Create_IO_Preview___Nate_Training   Traceback (most recent call last):     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 262, in   <module>       bigquery()     File   "/home/cjones8/starthinker/util/project/__init__.py", line 475, in   from_parameters_wrapper       func()     File "/home/cjones8/starthinker/task/bigquery/run.py",   line 255, in bigquery       bigquery_query()     File   "/home/cjones8/starthinker/task/bigquery/run.py", line 184, in   bigquery_query       rows     File   "/home/cjones8/starthinker/util/sheets/__init__.py", line 116, in   sheets_write       body = {'values':   list(data)}     File   "/home/cjones8/starthinker/util/csv/__init__.py", line 245, in   rows_to_type       for row in rows:     File   "/home/cjones8/starthinker/util/bigquery/__init__.py", line 760, in   query_to_rows       projectId=project_id,   body=body).execute()     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 386,   in execute       self.response =   API_Retry(self.job)     File   "/home/cjones8/starthinker/util/google_api/__init__.py", line 91,   in API_Retry       data = job.execute()     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/_helpers.py",   line 134, in positional_wrapper       return   wrapped(*args, **kwargs)     File   "/home/cjones8/starthinker_virtualenv/lib/python3.7/site-packages/googleapiclient/http.py",   line 915, in execute       raise   HttpError(resp, content, uri=self.uri)   googleapiclient.errors.HttpError:   <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sc-amea-usr-starthin-natstavn/queries?alt=json   returned "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.DV_IO_Insert_Review   was not found in location US". Details: "Not found: Table   sc-amea-usr-starthin-natstavn:Create_IO_Preview___Nate_Training.DV_IO_Insert_Review   was not found in location US"

**Comment by pkenjora** [comment]
This entire workflow is migrating to the new cm_to_dv task.  We'll review this issue in the new task if ti still exists.
