### ISSUE TITLE
Google Sheet Filters are Not Reliable

### ISSUE THREAD

**Issue by sopwilso** [google/starthinker#52]
Not sure if this should be logged here or under Google Sheet's github. Of the StarThinker recipes that integrate with Google Sheets to display data, the filter feature within sheets is not always reliable. 

Use case: User loads a large number of Line Items (rows) within the DV360 Bulk Editor recipe, and needs to be able to sort A-Z or filter on a key value. 

Issue seen: Filter on Line Item column within template does not even list the available values, only sees blanks. User is not able to sort or filter as a result. 

Priority: Not a critical bug or blocker.

**Comment by pkenjora** [comment]
Sophie,

  Please reach out to the [Google Sheets Forum](https://support.google.com/docs/community/?hl=en&gpf=%23!forum%2Fdocs).  Fortunately Google Sheets is a fully supported product so an answer for filters is likely.  Unfortunately its outside our scope.

- Paul
